In [1]:
import pandas as pd
import yaml

from internalizer import Internalizer
from internalizer.calculation_setup import *
from internalizer.regionalization import REMIND_REGIONS
from internalizer.utils import check_monetization_factors
import time

In [2]:
from internalizer.internalizer import CONFIG_NO_REMOVAL

In [3]:
EI_VERSION = "3.10"

mifpath = "/p/tmp/davidba/internalization_develop/remind/output/SSP2-NPi-internalize-combined_2025-09-19_11.34.29/lca/remind_runs/remind_SSP2-NPi-internalize-combined.mif"
gdxpath = "/p/tmp/davidba/internalization_develop/remind/output/SSP2-NPi-internalize-combined_2025-09-19_11.34.29/input.gdx"
pathway = "SSP2-NPi-internalize-combined"
monetization = 0.5
# monetization = {
#     "ReCiPe 2016 v1.03, midpoint (H) - acidification: terrestrial - terrestrial acidification potential (TAP)" : 5.27,
#   #   "ReCiPe 2016 v1.03, midpoint (H) - ecotoxicity: terrestrial - terrestrial ecotoxicity potential (TETP)": 6.4e-05
# }
plca = False
calcCosts = True
aggTaxes = True
# years = [2020, 2030, 2040, 2050]
years = [2020, 2030, 2050]
yaml_file = "../internalizer/data/mappings/remind_internalization_setup_v2.yaml"
levels = "SE,FE"


# set up brightway project
bw_project = f"internalizer_ei_{EI_VERSION}"

In [4]:
IMPACT_CATEGORIES_MC = [
    "acidification",
    "climate change",
    "ecotoxicity",
    "eutrophication",
    "fossil resources",
    "human toxicity",
    "ionizing radiation",
    "land use",
    "metal/mineral resources",
    "ozone depletion",
    "particulate matter formation",
    "photochemical oxidant formation",
    "water use"
]

In [5]:
# initialize Internalizer
I = Internalizer(
    mifpath,
    "remind",
    pathway,
    EI_VERSION,
    bw_project,
    gdxpath,
    outputfolder = "lca_v2"
)
print(I.scenario)

SSP2-NPi-internalize-combined

In [16]:

if plca:
    t0 = time.time()
    # add_ES_subcategories(mifpath)
    I.run_premise(years)
    t1 = time.time()
    print(f"Premise runs done in {t1-t0} seconds", "\n")

else:
    I.years = years

I.set_calculation_setup(levels=levels) # defaults to REMIND Internalization setup
print("Calculation setup set", "\n")

if calcCosts:
    t0 = time.time()
    I.calculate_costs(monetization, save_intermediate_results=True)
    t1 = time.time()
    print(f"Cost calculation done in {t1-t0} seconds", "\n")

if aggTaxes:
    t0 = time.time()
    I.load_costs()

    ics = IMPACT_CATEGORIES_MC
    if isinstance(monetization, dict):
        ics = list(monetization.keys())
    I.write_remind_input_files(
        2020,
        2030,
        ics
    )
    t1 = time.time()
    print(f"Tax recalculation done in {t1-t0} seconds", "\n")

Calculation setup set

se2h2, 2020: Matrices loaded
se2h2, 2020: Functional units selected
pe2se, 2050: Matrices loaded
pe2se, 2050: Functional units selected
pe2se, 2050: 0 activities in the removal list
pe2se, 2020: Matrices loaded
pe2se, 2020: Functional units selected
pe2se, 2020: 0 activities in the removal list
pe2se, 2030: Matrices loaded
pe2se, 2030: Functional units selected
pe2se, 2030: 0 activities in the removal list
se2h2, 2020: 4446 activities in the removal list
se2h2, 2020: LCI done.
se2h2, 2020: Cost calculation done.
se2h2, 2020: Regionalization done.
se2h2, 2030: Matrices loaded
se2h2, 2030: Functional units selected
se2h2, 2030: 4446 activities in the removal list
se2h2, 2030: LCI done.
se2h2, 2030: Cost calculation done.
se2h2, 2030: Regionalization done.
se2h2, 2050: Matrices loaded
se2h2, 2050: Functional units selected
se2h2, 2050: 4446 activities in the removal list
se2h2, 2050: LCI done.
se2h2, 2050: Cost calculation done.
se2h2, 2050: Regionalization done.
h22se, 2020: Matrices loaded
h22se, 2020: Functional units selected
h22se, 2020: 4431 activities in the removal list
h22se, 2020: LCI done.
h22se, 2020: Cost calculation done.
h22se, 2020: Regionalization done.
h22se, 2030: Matrices loaded
h22se, 2030: Functional units selected
h22se, 2030: 4431 activities in the removal list
h22se, 2030: LCI done.
h22se, 2030: Cost calculation done.
h22se, 2030: Regionalization done.
h22se, 2050: Matrices loaded
h22se, 2050: Functional units selected
h22se, 2050: 4431 activities in the removal list
h22se, 2050: LCI done.
h22se, 2050: Cost calculation done.
h22se, 2050: Regionalization done.
fe, 2020: Matrices loaded
fe, 2020: Functional units selected
fe, 2020: 4313 activities in the removal list
pe2se, 2020: LCI done.
pe2se, 2030: LCI done.
pe2se, 2050: LCI done.
fe, 2020: LCI done.
pe2se, 2020: Cost calculation done.
pe2se, 2030: Cost calculation done.
pe2se, 2020: Regionalization done.
pe2se, 2030: Regionalization done.
pe2se, 2050: Cost calculation done.
pe2se, 2050: Regionalization done.
fe, 2030: Matrices loaded
fe, 2030: Functional units selected
fe, 2030: 4313 activities in the removal list
fe, 2050: Matrices loaded
fe, 2050: Functional units selected
fe, 2050: 4313 activities in the removal list
fe, 2020: Cost calculation done.
fe, 2020: Regionalization done.
fe, 2030: LCI done.
fe, 2050: LCI done.
fe, 2030: Cost calculation done.
fe, 2050: Cost calculation done.
fe, 2030: Regionalization done.
fe, 2050: Regionalization done.
Cost calculation done in 189.84020853042603 seconds

Tax recalculation done in 1.0616350173950195 seconds

In [13]:
I.load_costs()

In [14]:
I

In [9]:
I.cs.levels

['pe2se', 'se2h2', 'h22se', 'fe']

In [7]:
I.cs.data["fe"]["removal list"]

,dataset name,dataset reference product,dataset unit
0,"biodiesel production, via Fischer-Tropsch, fro...","biodiesel, from forest residues",kilogram
1,"biodiesel production, via Fischer-Tropsch, fro...","biodiesel, from forest residues",kilogram
2,"biodiesel production, via transesterification,...","biodiesel, from algae",kilogram
3,"biodiesel production, via transesterification,...","biodiesel, from palm oil",kilogram
4,"biodiesel production, via transesterification,...","biodiesel, from rapeseed oil",kilogram
...,...,...,...
730,"wood chips production, hardwood, at sawmill","wood chips, wet, measured as dry mass",kilogram
731,"wood chips production, softwood, at sawmill","wood chips, wet, measured as dry mass",kilogram
732,wood pellet production,"wood pellet, measured as dry mass",kilogram
733,"wood pellets, burned in stirling heat and powe...","electricity, low voltage",kilowatt hour
734,"wood pellets, burned in stirling heat and powe...","heat, future",megajoule

In [28]:
# load raw costs and aggregate with mappings
I.cost_results = {}
for lvl in I.cs.levels:
    I.cost_results[lvl] = {}
    for year in I.years:
        # recalculate mapping
        mapping = I.cs.data[lvl].get(
            "regionalized mapping", I.cs.regionalize_dynamic_mapping(lvl, year)
        )
        fp = I.outdir + f"/{I.model}/{I.scenario}/{str(year)}/regionalized_costs_{lvl}.csv"
        regionalized_costs = pd.read_csv(fp)
        costs_agg = combine_shares_and_costs(mapping, regionalized_costs).melt(
            var_name="impact category", value_name="cost", ignore_index=False
        ).reset_index()
        I.cost_results[lvl][year] = costs_agg.set_index(
            ["REMIND index", "region", "impact category"]
        )["cost"].to_xarray()

In [12]:
mapping = I.cs.data["fe"]["base mapping"]


# extend mapping
dflist = []
for region in REMIND_REGIONS:
    df = mapping.copy()
    df["region"] = region
    dflist.append(df)

regionalized_mapping = pd.concat(dflist).set_index(["scenario variable", "region"])

# load .mif
mif = pd.read_csv(mifpath, sep=";").rename(columns={"Region": "region", "Variable": "scenario variable"})
mifdata = mif.set_index(["scenario variable", "region"])[str(year)]

# select shared index (some regions don't have certain FE variables)
combined_idx = regionalized_mapping.index.intersection(mifdata.index)
sel = regionalized_mapping.loc[combined_idx]

# calculate shares
sel["weight"] = mifdata.loc[combined_idx]
sel = sel.reset_index()
sel["total"] = sel.reset_index().groupby(["REMIND index", "region"])["weight"].transform("sum")

# where total is zero, set weights to one and recalculate total
def robust_weights(row):
    if row["total"] == 0:
        return 1
    else:
        return row["weight"]
sel["weight new"] = sel.apply(robust_weights, axis=1)
sel["total new"] = sel.groupby(["REMIND index", "region"])["weight new"].transform("sum")
sel["share"] = sel["weight new"] / sel["total new"]

In [14]:
sel[sel["total"] == 0]

,scenario variable,region,REMIND index,dataset name,dataset reference product,dataset unit,share,weight,total,weight new,total new
4,FE|Buildings|Heating|Hydrogen,CAZ,build - feh2s,"heat, residential, by combustion of hydrogen u...","heat, from residential heating system",megajoule,1.000000,0.0,0.0,1.0,1.0
15,FE|CDR|DAC|+|Gases,CAZ,cdr - fegas,"heat production, natural gas, at boiler conden...","heat, district or industrial, natural gas",megajoule,0.500000,0.0,0.0,1.0,2.0
17,FE|CDR|DAC|+|Hydrogen,CAZ,cdr - feh2s,"heat production, from hydrogen-fired one gigaw...",heat,megajoule,0.333333,0.0,0.0,1.0,3.0
18,FE|CDR|EW|+|Diesel,CAZ,cdr - fedie,"diesel, burned in diesel-electric generating s...","diesel, burned in diesel-electric generating s...",megajoule,0.333333,0.0,0.0,1.0,3.0
20,"FE|CDR|OAE, electric calciner|+|Diesel",CAZ,cdr - fedie,"diesel, burned in diesel-electric generating s...","diesel, burned in diesel-electric generating s...",megajoule,0.333333,0.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...
2237,"FE|CDR|OAE, electric calciner|+|Diesel",USA,cdr - fedie,"diesel, burned in diesel-electric generating s...","diesel, burned in diesel-electric generating s...",megajoule,0.333333,0.0,0.0,1.0,3.0
2239,"FE|CDR|OAE, electric calciner|+|Hydrogen",USA,cdr - feh2s,"hydrogen, burned in gas turbine 1GW",heat,megajoule,0.333333,0.0,0.0,1.0,3.0
2240,"FE|CDR|OAE, traditional calciner|+|Diesel",USA,cdr - fedie,"diesel, burned in diesel-electric generating s...","diesel, burned in diesel-electric generating s...",megajoule,0.333333,0.0,0.0,1.0,3.0
2242,"FE|CDR|OAE, traditional calciner|+|Gases",USA,cdr - fegas,"natural gas, burned in gas turbine","natural gas, burned in gas turbine",megajoule,0.500000,0.0,0.0,1.0,2.0
2243,"FE|CDR|OAE, traditional calciner|+|Hydrogen",USA,cdr - feh2s,"hydrogen, burned in gas turbine 1GW",heat,megajoule,0.333333,0.0,0.0,1.0,3.0

In [9]:
lvl = "fe"
year = 2030
mapping = I.cs.data[lvl].get(
    "regionalized mapping", I.cs.regionalize_dynamic_mapping(lvl, year)
)

In [10]:
mapping

,REMIND index,dataset name,dataset reference product,dataset unit,share,region
0,build - fehes,"market for heat, district or industrial, natur...","heat, district or industrial, natural gas",megajoule,1.000000,CAZ
1,build - feels,"heat production, air-water heat pump 10kW","heat, air-water heat pump 10kW",megajoule,0.067934,CAZ
2,build - feels,"heat, residential, electric storage heater, us...","heat, from residential heating system",megajoule,0.225984,CAZ
3,build - fegas,"heat production, natural gas, at boiler conden...","heat, central or small-scale, natural gas",megajoule,1.000000,CAZ
4,build - feh2s,"heat, residential, by combustion of hydrogen u...","heat, from residential heating system",megajoule,1.000000,CAZ
...,...,...,...,...,...,...
2395,trans - fedie,"diesel, synthetic, burned in passenger car",heat,megajoule,0.000000,USA
2396,trans - feelt,"electricity, used in battery electric motorcycle","electricity, low voltage",megajoule,0.014162,USA
2397,trans - fepet,"bioethanol, burned in motorcycle",heat,megajoule,0.000094,USA
2398,trans - fepet,"petrol, burned in motorcycle",heat,megajoule,0.002531,USA
2399,trans - fepet,"petrol, synthetic, burned in motorcycle",heat,megajoule,0.000000,USA

In [30]:
regionalized_costs = regionalized_costs.pivot(
    index=["dataset name", "dataset reference product", "dataset unit", "region"],
    columns="impact category",
    values="cost"
)

In [31]:
regionalized_costs

impact category                                                                                   acidification  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ          0.000239
                                                                                          CHA          0.000257
                                                                                          EUR          0.000245
                                                                                          IND          0.000241
                                                                                          JPN          0.000263
...                                                                                                         ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS          0.000221
                                                                                          REF          0.000221
                                                                                          SSA          0.000221
                                                                                          USA          0.000221
                                                                                          World        0.000221

impact category                                                                                   climate change  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ           0.001880
                                                                                          CHA           0.002326
                                                                                          EUR           0.001781
                                                                                          IND           0.001926
                                                                                          JPN           0.002016
...                                                                                                          ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS           0.002214
                                                                                          REF           0.002214
                                                                                          SSA           0.002214
                                                                                          USA           0.002214
                                                                                          World         0.002214

impact category                                                                                   ecotoxicity  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ        0.000840
                                                                                          CHA        0.001096
                                                                                          EUR        0.000812
                                                                                          IND        0.000880
                                                                                          JPN        0.001059
...                                                                                                       ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS        0.000479
                                                                                          REF        0.000479
                                                                                          SSA        0.000479
                                                                                          USA        0.000479
                                                                                          World      0.000479

impact category                                                                                   eutrophication  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ           0.000081
                                                                                          CHA           0.000097
                                                                                          EUR           0.000089
                                                                                          IND           0.000087
                                                                                          JPN           0.000097
...                                                                                                          ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS           0.000138
                                                                                          REF           0.000138
                                                                                          SSA           0.000138
                                                                                          USA           0.000138
                                                                                          World         0.000138

impact category                                                                                   fossil resources  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ             0.001146
                                                                                          CHA             0.001139
                                                                                          EUR             0.001119
                                                                                          IND             0.001168
                                                                                          JPN             0.001196
...                                                                                                            ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS             0.000098
                                                                                          REF             0.000098
                                                                                          SSA             0.000098
                                                                                          USA             0.000098
                                                                                          World           0.000098

impact category                                                                                   human toxicity  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ           0.000259
                                                                                          CHA           0.000315
                                                                                          EUR           0.000267
                                                                                          IND           0.000260
                                                                                          JPN           0.000310
...                                                                                                          ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS           0.000856
                                                                                          REF           0.000856
                                                                                          SSA           0.000856
                                                                                          USA           0.000856
                                                                                          World         0.000856

impact category                                                                                   ionizing radiation  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ           9.374514e-07
                                                                                          CHA           1.913128e-06
                                                                                          EUR           8.626729e-07
                                                                                          IND           2.218212e-06
                                                                                          JPN           1.340936e-06
...                                                                                                              ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS           6.971429e-07
                                                                                          REF           6.971429e-07
                                                                                          SSA           6.971429e-07
                                                                                          USA           6.971429e-07
                                                                                          World         6.971429e-07

impact category                                                                                   land use  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ     0.000094
                                                                                          CHA     0.000116
                                                                                          EUR     0.000118
                                                                                          IND     0.000081
                                                                                          JPN     0.000114
...                                                                                                    ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS     0.000280
                                                                                          REF     0.000280
                                                                                          SSA     0.000280
                                                                                          USA     0.000280
                                                                                          World   0.000280

impact category                                                                                   metal/mineral resources  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ                    0.000091
                                                                                          CHA                    0.000109
                                                                                          EUR                    0.000086
                                                                                          IND                    0.000094
                                                                                          JPN                    0.000125
...                                                                                                                   ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS                    0.000043
                                                                                          REF                    0.000043
                                                                                          SSA                    0.000043
                                                                                          USA                    0.000043
                                                                                          World                  0.000043

impact category                                                                                   ozone depletion  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ        2.214180e-08
                                                                                          CHA        1.586860e-08
                                                                                          EUR        3.068578e-08
                                                                                          IND        2.200781e-08
                                                                                          JPN        2.340859e-08
...                                                                                                           ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS        2.131534e-09
                                                                                          REF        2.131534e-09
                                                                                          SSA        2.131534e-09
                                                                                          USA        2.131534e-09
                                                                                          World      2.131534e-09

impact category                                                                                   particulate matter formation  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ                         0.001336
                                                                                          CHA                         0.001514
                                                                                          EUR                         0.001358
                                                                                          IND                         0.001340
                                                                                          JPN                         0.001479
...                                                                                                                        ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS                         0.005216
                                                                                          REF                         0.005216
                                                                                          SSA                         0.005216
                                                                                          USA                         0.005216
                                                                                          World                       0.005216

impact category                                                                                   photochemical oxidant formation  \
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ                            0.000131
                                                                                          CHA                            0.000125
                                                                                          EUR                            0.000125
                                                                                          IND                            0.000129
                                                                                          JPN                            0.000140
...                                                                                                                           ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS                            0.000209
                                                                                          REF                            0.000209
                                                                                          SSA                            0.000209
                                                                                          USA                            0.000209
                                                                                          World                          0.000209

impact category                                                                                   water use
dataset name                                       dataset reference product dataset unit region
biodiesel, burned in heavy-duty vehicle            heat                      megajoule    CAZ      0.000053
                                                                                          CHA      0.000073
                                                                                          EUR      0.000044
                                                                                          IND      0.000046
                                                                                          JPN      0.000044
...                                                                                                     ...
soft wood chips from forest, burned in furnace ... heat                      megajoule    OAS      0.000041
                                                                                          REF      0.000041
                                                                                          SSA      0.000041
                                                                                          USA      0.000041
                                                                                          World    0.000041

[960 rows x 13 columns]

In [32]:
mapping = mapping.set_index(["dataset name", "dataset reference product", "dataset unit", "region"])

In [ ]:
old_idx = mapping.index
new_idx = []
for idx in old_idx:
    if idx in regionalized_costs.index:
        new_idx.append(idx)
    else:
        new_idx.append((idx[0], idx[1], idx[2], "World"))

In [ ]:
combined = pd.DataFrame(
    regionalized_costs.loc[new_idx].to_numpy(),
    index=old_idx,
    columns=regionalized_costs.columns
).mul(mapping["share"], axis=0)

In [ ]:
combined["REMIND index"] = mapping["REMIND index"]
combined

impact category                                                                                     ReCiPe 2016 v1.03, midpoint (H) - acidification: terrestrial - terrestrial acidification potential (TAP)  \
dataset name                                       dataset reference product  dataset unit  region
electricity production, natural gas, combined c... electricity, high voltage  kilowatt hour CAZ                                              0.000213
electricity production, at natural gas-fired co... electricity, high voltage  kilowatt hour CAZ                                              0.000271
electricity production, natural gas, convention... electricity, high voltage  kilowatt hour CAZ                                              0.000496
petroleum and gas production, onshore              natural gas, high pressure cubic meter   CAZ                                              0.000034
petroleum and gas production, offshore             natural gas, high pressure cubic meter   CAZ                                              0.000011
...                                                                                                                                               ...
ethanol production, via fermentation, from misc... ethanol, from miscanthus   kilogram      LAM                                              0.000727
                                                                                            MEA                                              0.000894
                                                                                            OAS                                              0.000844
                                                                                            SSA                                              0.000981
                                                                                            USA                                              0.000310

impact category                                                                                    REMIND index
dataset name                                       dataset reference product  dataset unit  region
electricity production, natural gas, combined c... electricity, high voltage  kilowatt hour CAZ            ngcc
electricity production, at natural gas-fired co... electricity, high voltage  kilowatt hour CAZ           ngccc
electricity production, natural gas, convention... electricity, high voltage  kilowatt hour CAZ             ngt
petroleum and gas production, onshore              natural gas, high pressure cubic meter   CAZ           gastr
petroleum and gas production, offshore             natural gas, high pressure cubic meter   CAZ           gastr
...                                                                                                         ...
ethanol production, via fermentation, from misc... ethanol, from miscanthus   kilogram      LAM         bioethl
                                                                                            MEA         bioethl
                                                                                            OAS         bioethl
                                                                                            SSA         bioethl
                                                                                            USA         bioethl

[988 rows x 2 columns]

In [ ]:
combined.reset_index().groupby(["REMIND index", "region"])[regionalized_costs.columns].sum()

impact category      ReCiPe 2016 v1.03, midpoint (H) - acidification: terrestrial - terrestrial acidification potential (TAP)
REMIND index region
MeOH         CAZ                                              0.002039
             CHA                                              0.002040
             EUR                                              0.002040
             IND                                              0.002040
             JPN                                              0.002040
...                                                                ...
windoff      NEU                                              0.000142
             OAS                                              0.000142
             REF                                              0.000142
             SSA                                              0.000142
             USA                                              0.000142

[624 rows x 1 columns]

In [ ]:
mapping.share

dataset name                                                                                                  dataset reference product   dataset unit   region
electricity production, natural gas, combined cycle power plant                                               electricity, high voltage   kilowatt hour  CAZ       1.0
electricity production, at natural gas-fired combined cycle power plant, post, pipeline 200km, storage 1000m  electricity, high voltage   kilowatt hour  CAZ       1.0
electricity production, natural gas, conventional power plant                                                 electricity, high voltage   kilowatt hour  CAZ       1.0
petroleum and gas production, onshore                                                                         natural gas, high pressure  cubic meter    CAZ       0.7
petroleum and gas production, offshore                                                                        natural gas, high pressure  cubic meter    CAZ       0.3
                                                                                                                                                                  ...
ethanol production, via fermentation, from miscanthus, energy allocation                                      ethanol, from miscanthus    kilogram       LAM       0.7
                                                                                                                                                         MEA       0.8
                                                                                                                                                         OAS       0.8
                                                                                                                                                         SSA       0.9
                                                                                                                                                         USA       0.3
Name: share, Length: 988, dtype: float64

In [ ]:
combined.mul(mapping["share"], axis=0)

impact category                                                                                     ReCiPe 2016 v1.03, midpoint (H) - acidification: terrestrial - terrestrial acidification potential (TAP)
dataset name                                       dataset reference product  dataset unit  region
electricity production, natural gas, combined c... electricity, high voltage  kilowatt hour CAZ                                              0.000213
electricity production, at natural gas-fired co... electricity, high voltage  kilowatt hour CAZ                                              0.000271
electricity production, natural gas, convention... electricity, high voltage  kilowatt hour CAZ                                              0.000496
petroleum and gas production, onshore              natural gas, high pressure cubic meter   CAZ                                              0.000034
petroleum and gas production, offshore             natural gas, high pressure cubic meter   CAZ                                              0.000011
...                                                                                                                                               ...
ethanol production, via fermentation, from misc... ethanol, from miscanthus   kilogram      LAM                                              0.000727
                                                                                            MEA                                              0.000894
                                                                                            OAS                                              0.000844
                                                                                            SSA                                              0.000981
                                                                                            USA                                              0.000310

[988 rows x 1 columns]

In [ ]:
global_idx = mapping.index.difference(regionalized_costs.index)
idx_frame = global_idx.to_frame().set_index(np.arange(len(global_idx)))
idx_frame["region"] = "World"

new_index = pd.MultiIndex.from_frame(idx_frame).union(mapping.index.intersection(regionalized_costs.index))
new_index

MultiIndex([(    'biodiesel production, via transesterification, from palm oil, energy allocation', ...),
            (    'biodiesel production, via transesterification, from palm oil, energy allocation', ...),
            (    'biodiesel production, via transesterification, from palm oil, energy allocation', ...),
            (    'biodiesel production, via transesterification, from palm oil, energy allocation', ...),
            (    'biodiesel production, via transesterification, from palm oil, energy allocation', ...),
            ('biodiesel production, via transesterification, from rapeseed oil, energy allocation', ...),
            ('biodiesel production, via transesterification, from rapeseed oil, energy allocation', ...),
            ('biodiesel production, via transesterification, from rapeseed oil, energy allocation', ...),
            ('biodiesel production, via transesterification, from rapeseed oil, energy allocation', ...),
            ('biodiesel production, via transesterification, from rapeseed oil, energy allocation', ...),
            ...
            (                                                             'wood pellet production', ...),
            (                                                             'wood pellet production', ...),
            (                                                             'wood pellet production', ...),
            (                                                             'wood pellet production', ...),
            (                                                             'wood pellet production', ...),
            (                                                             'wood pellet production', ...),
            (                                                             'wood pellet production', ...),
            (                                                             'wood pellet production', ...),
            (                                                             'wood pellet production', ...),
            (                                                             'wood pellet production', ...)],
           names=['dataset name', 'dataset reference product', 'dataset unit', 'region'], length=964)

In [ ]:
mapping["share"]

dataset name                                                                                                  dataset reference product   dataset unit   region
electricity production, natural gas, combined cycle power plant                                               electricity, high voltage   kilowatt hour  CAZ       1.0
electricity production, at natural gas-fired combined cycle power plant, post, pipeline 200km, storage 1000m  electricity, high voltage   kilowatt hour  CAZ       1.0
electricity production, natural gas, conventional power plant                                                 electricity, high voltage   kilowatt hour  CAZ       1.0
petroleum and gas production, onshore                                                                         natural gas, high pressure  cubic meter    CAZ       0.7
petroleum and gas production, offshore                                                                        natural gas, high pressure  cubic meter    CAZ       0.3
                                                                                                                                                                  ...
ethanol production, via fermentation, from miscanthus, energy allocation                                      ethanol, from miscanthus    kilogram       LAM       0.7
                                                                                                                                                         MEA       0.8
                                                                                                                                                         OAS       0.8
                                                                                                                                                         SSA       0.9
                                                                                                                                                         USA       0.3
Name: share, Length: 988, dtype: float64

In [ ]:
regionalized_costs.loc[new_index]

impact category                                                                                           ReCiPe 2016 v1.03, midpoint (H) - acidification: terrestrial - terrestrial acidification potential (TAP)
dataset name                                       dataset reference product         dataset unit region
biodiesel production, via transesterification, ... biodiesel, from palm oil          kilogram     IND                                              0.001617
                                                                                                  LAM                                              0.001534
                                                                                                  MEA                                              0.001690
                                                                                                  OAS                                              0.001581
                                                                                                  SSA                                              0.001646
...                                                                                                                                                     ...
wood pellet production                             wood pellet, measured as dry mass kilogram     World                                            0.000064
                                                                                                  World                                            0.000064
                                                                                                  World                                            0.000064
                                                                                                  World                                            0.000064
                                                                                                  World                                            0.000064

[964 rows x 1 columns]

In [ ]:
Q = np.random.random((1, 100))
Imat = np.random.random((100, 50))

In [ ]:
(Q @ Imat).sum(axis=-1)

array([1388.29838872])

In [ ]:
import xarray as xr

In [ ]:
methods = list(monetization.keys())

In [ ]:
impacts = xr.DataArray(
    (Q @ Imat).sum(axis=-1),
    coords = {
        "LCIA method": methods
    }
)

In [ ]:
mfs = xr.DataArray(
    np.diag(list(monetization.values())),
    {
        "LCIA method": methods,
        "impact category": methods
    }
)

In [ ]:
(mfs * impacts).sum(dim="LCIA method").to_dataframe(name="cost").reset_index()

                                     impact category         cost
0  ReCiPe 2016 v1.03, midpoint (H) - acidificatio...  7316.332509